### ISSUE TITLE
Error in updateros.py

### ISSUE THREAD

**Issue by netsound** [kd7lxl/python-amprapi#3]
Getting the following when trying to run the updater all of a sudden.   Tried cloning into a new VM and same errors.  Wonder if a package changed in python.

Traceback (most recent call last):
  File "./updateros.py", line 176, in <module>
    main()
  File "./updateros.py", line 106, in main
    encap = filter(None, map(filter_encap, get_encap()))
  File "./updateros.py", line 42, in get_encap
    ampr = amprapi.AMPRAPI()
  File "/home/fmoses/python-amprapi/amprapi.py", line 72, in **init**
    self.enforce_version()
  File "/home/fmoses/python-amprapi/amprapi.py", line 78, in enforce_version
    if not self.check_version():
  File "/home/fmoses/python-amprapi/amprapi.py", line 75, in check_version
    return self._api_version_minor == self.get('version')['version']
  File "/home/fmoses/python-amprapi/amprapi.py", line 87, in get
    return json.loads(r.json())
  File "/usr/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

**Comment by kd7lxl** [comment]
I'm not on a computer where I can check  but I bet the API version on the source changed.

**Comment by netsound** [comment]
What I am thinking... I hadn't checked it in awhile so not sure when it started failing..

**Comment by yo2loj** [comment]
I assume you did some python upgrades...
- Check in amprapi.py (line 63) that _api_version_minor is set to “1.0.7”
- In amprapi.py  (line 87) replace
  return json.loads(r.json())
  with
  return json.loads(r.text)

LE: It is actually the ampr API that changed some time ago...

Marius, YO2LOJ

**Comment by netsound** [comment]
Yea I am sure a package updated.  Changes made worked like a charm...

**Comment by yo2loj** [comment]
This issue should be reopened and changes added to the master to fit the latest 1.0.7 API

**Comment by kd7lxl** [comment]
Do you have a patch that reflects these changes?

**Comment by yo2loj** [comment]
I created a pull request for the changes in Git

**Comment by mstorck** [comment]
seems to be solved by now. I suggest closing this issue.

**Comment by kd7lxl** [comment]
There are no changes tagged with this issue. How could have been solved?

Edit: Was this fixed in a5733f4?

**Comment by mstorck** [comment]
I seems to have been fixed a pull request created by YO2LOJ

https://github.com/kd7lxl/python-amprapi/pull/4/files
https://github.com/kd7lxl/python-amprapi/commit/d84daa1e9f98645ff9e39be504a51311c88ecf2b

which was merged on November 23.

Edit: this seems to correlate to https://github.com/kd7lxl/python-amprapi/commit/a5733f469d19388109fe1a50f7843531b3663eba
