### ISSUE TITLE
KeyError: u'netmask' using latest commit (d84daa1 on Nov 23, 2015)

### ISSUE THREAD

**Issue by n00tz** [kd7lxl/python-amprapi#5]
Command run:
pi@raspberrypi:~/amprapi $ ./amprapi.py -n -v 192.168.111.1

Traceback (most recent call last):
 File "./amprapi.py", line 100, in <module>
   print "%(network)s/%(netmask)s via %(gatewayIP)s" % entry
 File "/usr/lib/python2.7/UserDict.py", line 23, in **getitem**
   raise KeyError(key)
KeyError: u'netmask'

**Comment by kd7lxl** [comment]
I haven't been able to reproduce this.

**Comment by yo2loj** [comment]
Somehow an error slipped in the last version:
Line 100 in GIT which shows the error:
print "%(network)s/%(netmask)s via %(gatewayIP)s" % entry

Corrected functional:
print "%(network)s/%(maskLength)s via %(gatewayIP)s" % entry

**Comment by kd7lxl** [comment]
AMPR API originally used the key `netmask`. Version 1.01 added the key `maskLength`. It appears a recent API version dropped `netmask` altogether, but this is not reflected in the change log.
